services:
                        
    admin.menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminMenu
        tags:
            - { name: knp_menu.menu, alias: adminMenu }
            
    admin.menu.category:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminCategoryMenu
        tags:
            - { name: knp_menu.menu, alias: adminCategoryMenu }
            
    admin.menu.manufacturer:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminManufacturerMenu
        tags:
            - { name: knp_menu.menu, alias: adminManufacturerMenu }
            
    admin.menu.product_attachment:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminProductAttachmentMenu
        tags:
            - { name: knp_menu.menu, alias: adminProductAttachmentMenu }
            
    admin.menu.product_type:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminProductTypeMenu
        tags:
            - { name: knp_menu.menu, alias: adminProductTypeMenu }
            
    admin.menu.product:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminProductMenu
        tags:
            - { name: knp_menu.menu, alias: adminProductMenu }
            
    admin.menu.user:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: adminUserMenu
        tags:
            - { name: knp_menu.menu, alias: adminUserMenu }

